services:
  blog_strapi_api:
    container_name: blog_strapi_api
    hostname: blog_strapi_api
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: blog-strapi
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - C:/Users/Industria 4.0/Documents/Docker:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432